### ISSUE TITLE
关于性能的问题

### ISSUE THREAD

**Issue by woaicv** [dq0309/PSTQE#2]
您好，非常感谢您的工作！有个问题是您的训练速度大概多久？您的这个模型和stdf相比如何？因为我看到您的训练的数据好像和目前复现的stdf的训练数据不一致

**Comment by dq0309** [comment]
我的训练数据是MFQE2.0提供的训练数据

**Comment by dq0309** [comment]
学习率设置为0.001，Adam优化器，1080Ti显卡，训练60-70epoch就差不多收敛，应该10几个小时左右。在相同的数据集下，和STDF-R1相当，且PSTQE的参数量显著低于STDF-R1。采用的训练数据是MFQE2.0提供的视频数据。
不好意思，没有及时回复。有任何问题，欢迎提问。

**Comment by dq0309** [comment]
在LDP上的增强结果，您还可以下载上传的模型进行测试获得。

**Comment by woaicv** [comment]
谢谢您的回复，还有个问题：关于BD-Rate Reduction您是怎么计算的？我刚做视频增强，对于压缩还不太懂。

**Comment by dq0309** [comment]
关于BD-rate的计算，您可以在github主页搜索。
